[platformio]
src_dir = examples/Minipirate
lib_dir = .
default_envs = native, uno, pico, nucleo_g431rb

[env:native]
platform = native
test_framework = unity
test_build_src = no
build_flags =
    -I test/mocks
    -D NATIVE_TEST

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    Servo

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
lib_deps =
    Servo

[env:nucleo_g431rb]
platform = ststm32
board = nucleo_g431rb
framework = arduino
lib_deps =
    Servo
